# Generated by Django 6.0.3 on 2026-04-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgame',
            name='genre_id',
        ),
        migrations.AddField(
            model_name='boardgame',
            name='genre_id',
            field=models.ManyToManyField(related_name='games', to='game_list.genre'),
        ),
    ]
