# Generated by Django 6.0.3 on 2026-04-13 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_list', '0002_remove_boardgame_genre_id_boardgame_genre_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardgame',
            options={'ordering': ['-created_at']},
        ),
    ]
