# Generated by Django 6.0.3 on 2026-04-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_list', '0003_alter_boardgame_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
