# Generated by Django 6.0.3 on 2026-04-22 10:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_list', '0004_boardgame_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
