# Generated by Django 6.0.3 on 2026-04-22 11:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_list', '0005_boardgame_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
