# Generated by Django 6.0.3 on 2026-04-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_list', '0007_alter_boardgame_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgame',
            name='status',
        ),
        migrations.AddField(
            model_name='boardgame',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
