# Generated by Django 6.0.3 on 2026-04-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_list', '0008_remove_boardgame_status_boardgame_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
