# Generated by Django 6.0.3 on 2026-04-24 10:40

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_list', '0009_alter_boardgame_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='description',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
