# Generated by Django 6.0.3 on 2026-04-16 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_sessions', '0002_playsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playsession',
            name='first_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_place_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playsession',
            name='second_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_place_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playsession',
            name='third_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_place_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
