# Generated by Django 6.0.3 on 2026-04-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_sessions', '0003_playsession_first_place_playsession_second_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playsession',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
