# Generated by Django 6.0.3 on 2026-04-26 15:05

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_comment', '0003_comment_approved_review_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
