# Generated by Django 6.0.3 on 2026-04-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_comment', '0004_alter_comment_content_alter_review_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(),
        ),
    ]
